// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqCN51lGWfthHLYKpymEUXBs99ExIqXI',
    appId: '1:1024811004412:web:fc74ea9135cefcb6724279',
    messagingSenderId: '1024811004412',
    projectId: 'carculb-1080f',
    authDomain: 'carculb-1080f.firebaseapp.com',
    storageBucket: 'carculb-1080f.firebasestorage.app',
    measurementId: 'G-NM74C9SZF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjKm_irs5Ip8KneQAofvzt7d7GFw6q6b8',
    appId: '1:1024811004412:android:a4d00ea83128ede8724279',
    messagingSenderId: '1024811004412',
    projectId: 'carculb-1080f',
    storageBucket: 'carculb-1080f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Cct6J2pvF7Qc2ZI5ayl20fh0gZWQspU',
    appId: '1:1024811004412:ios:8cb1c3d63073bb2c724279',
    messagingSenderId: '1024811004412',
    projectId: 'carculb-1080f',
    storageBucket: 'carculb-1080f.firebasestorage.app',
    iosBundleId: 'com.example.carClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Cct6J2pvF7Qc2ZI5ayl20fh0gZWQspU',
    appId: '1:1024811004412:ios:8cb1c3d63073bb2c724279',
    messagingSenderId: '1024811004412',
    projectId: 'carculb-1080f',
    storageBucket: 'carculb-1080f.firebasestorage.app',
    iosBundleId: 'com.example.carClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiqCN51lGWfthHLYKpymEUXBs99ExIqXI',
    appId: '1:1024811004412:web:aff4ee80c4a52fa2724279',
    messagingSenderId: '1024811004412',
    projectId: 'carculb-1080f',
    authDomain: 'carculb-1080f.firebaseapp.com',
    storageBucket: 'carculb-1080f.firebasestorage.app',
    measurementId: 'G-YJK66WC9D4',
  );

  
}
